### ISSUE TITLE
Dark Mode looks bad

### ISSUE THREAD

**Issue by daviddelmonte** [thierryH91200/ModernLookOSXSampleSwift#2]
It would be great if this project could be upgraded to support both light and dark modes. It's a very useful tool for me.

**Comment by thierryH91200** [comment]
under construction

https://github.com/kaunteya/MacSystemColors

**Comment by daviddelmonte** [comment]
Thanks for the link. Very helpful.

**Comment by daviddelmonte** [comment]
You fixed it in no time! Thanks so much. I'm using the controls as a template for some old apps I need to bring up to date.
