### ISSUE TITLE
Crash when using Xcode 11.4 beta

### ISSUE THREAD

**Issue by daviddelmonte** [thierryH91200/ModernLookOSXSampleSwift#3]
Thierry, in the new Xcode beta, a hang occurs when tapping the clock icon next to settings. I have to Force-Quit ML. Then I also have to Force-Quit Xcode. I realize that this may be an Apple issue, but just in case...

<img width="366" alt="Screen Shot 2020-02-06 at 10 49 27 AM" src="https://user-images.githubusercontent.com/114487/73953561-98aa9380-48ce-11ea-8178-69d21b173cb7.png">

**Comment by thierryH91200** [comment]
tap Esc I look for for the issue

**Comment by thierryH91200** [comment]
resolved
